server:
  port: ${PORT:8080}

spring:
  application:
    name: service-uploads
  data:
    mongodb:
      uri: mongodb+srv://service-uploads:8QCEmWsF4UwokQuc@fiapx-cluster.r1ydsi7.mongodb.net/fiapx
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME:}
    password: ${EMAIL_PASSWORD:}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

aws:
  region: us-east-1
  sqs:
    endpoint: ${AWS_SQS_ENDPOINT:https://sqs.us-east-1.amazonaws.com/828818793977/uploads-events}
    fileProcessorQueueUrl: ${AWS_SQS_FILE_PROCESSOR_QUEUE_URL:https://sqs.us-east-1.amazonaws.com/828818793977/files-processor-events}