apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-uploads-app
  labels:
    app: service-uploads-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-uploads-app
  template:
    metadata:
      labels:
        app: service-uploads-app
    spec:
      containers:
        - name: app
          image: 828818793977.dkr.ecr.us-east-1.amazonaws.com/service-uploads-repo:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "500m"
            limits:
              cpu: "1000m"
          env:
            - name: MONGO_DB_USER
              valueFrom:
                secretKeyRef:
                  name: service-uploads-secrets
                  key: MONGO_DB_USER
            - name: MONGO_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: service-uploads-secrets
                  key: MONGO_DB_PASSWORD
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: service-uploads-secrets
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: service-uploads-secrets
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_SESSION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: service-uploads-secrets
                  key: AWS_SESSION_TOKEN