apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: service-uploads-monitor
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: service-uploads
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s